CREATE TABLE TB_USER(
	USER_NO     NUMBER CONSTRAINT TB_USER_PK PRIMARY KEY,
	USER_ID     VARCHAR2(30) NOT NULL,
	USER_PW     VARCHAR2(30) NOT NULL,
	USER_NAME   VARCHAR2(30) NOT NULL,
	ENROLL_DATE DATE DEFAULT CURRENT_DATE
);

COMMENT ON COLUMN TB_USER.USER_NO     IS '사용자 번호';
COMMENT ON COLUMN TB_USER.USER_ID     IS '사용자 아이디';
COMMENT ON COLUMN TB_USER.USER_PW     IS '사용자 비밀번호';
COMMENT ON COLUMN TB_USER.USER_NAME   IS '사용자 이름';
COMMENT ON COLUMN TB_USER.ENROLL_DATE IS '사용자 가입일';


-- USER_NO 컬럼에 삽입될 시퀀스 생성
CREATE SEQUENCE SEQ_USER_NO NOCACHE;

-- 샘플 데이터 INSERT
INSERT INTO TB_USER 
VALUES(SEQ_USER_NO.NEXTVAL, 'user01', 'pass01', '유저일', DEFAULT );
INSERT INTO TB_USER 
VALUES(SEQ_USER_NO.NEXTVAL, 'user02', 'pass02', '유저이', DEFAULT );

SELECT * FROM TB_USER;

COMMIT;


DROP TABLE TB_USER;
DROP SEQUENCE SEQ_USER_NO;


SELECT USER_NO, USER_ID, USER_PW, USER_NAME,
TO_CHAR(ENROLL_DATE, 'YYYY"년" MM"월" DD"일"') ENROLL_DATE
FROM TB_USER
WHERE USER_NO = 1
ORDER BY USER_NO;


SELECT USER_NAME
FROM TB_USER
WHERE USER_NAME LIKE '___%';

SELECT USER_NAME 
FROM TB_USER 
WHERE USER_NAME LIKE '%유%';

DELETE FROM TB_USER
WHERE USER_NO = 2;

SELECT * FROM TB_USER;

SELECT COUNT(*)
FROM TB_USER
WHERE USER_ID = 'userSDGDS';
-- 행의 결과 값인 1 또는 0의 데이터 값을 가지고 갈 거기 때문에 int형 사용


CREATE TABLE KH_STUDENT (
STD_NO NUMBER PRIMARY KEY,
STD_NAME NVARCHAR2(5) NOT NULL,
STD_AGE NUMBER NOT NULL,
MAJOR NVARCHAR2(10) NOT NULL,
ENT_DATE DATE DEFAULT SYSDATE
);

-- NVARCHAR2 : 유니코드 문자 집합을 사용하여 한글 사용 시 깨지지 않음
-- ㄴ 한 문자당 2byte

CREATE SEQUENCE SEQ_STUDENT_NO NOCACHE;

SELECT * FROM KH_STUDENT;

INSERT INTO KH_STUDENT
VALUES(SEQ_STUDENT_NO.NEXTVAL, '홍길동', 20, '개발', DEFAULT);

INSERT INTO KH_STUDENT
VALUES(SEQ_STUDENT_NO.NEXTVAL, '페이커', 30, '개발', DEFAULT);

INSERT INTO KH_STUDENT
VALUES(SEQ_STUDENT_NO.NEXTVAL, '이세돌', 35, '개발', DEFAULT);

INSERT INTO KH_STUDENT
VALUES(SEQ_STUDENT_NO.NEXTVAL, '임영웅', 29, '가수', DEFAULT);

INSERT INTO KH_STUDENT
VALUES(SEQ_STUDENT_NO.NEXTVAL, '이수지', 37, '개그맨', DEFAULT);

SELECT STD_NO, STD_NAME, STD_AGE, MAJOR, ENT_DATE
FROM KH_STUDENT;

UPDATE KH_STUDENT
SET STD_NAME = '페이커', STD_AGE = '30', MAJOR = '프로게이머'
WHERE STD_NO = 3;

DELETE FROM KH_STUDENT
WHERE STD_NO = 8;

SELECT STD_NO
FROM KH_STUDENT
WHERE STD_NO = 3;

SELECT STD_NO, STD_NAME, STD_AGE, MAJOR, ENT_DATE
FROM KH_STUDENT
WHERE MAJOR = '개발' AND MAJOR LIKE '개발%';

COMMIT;